fos_js_routing:
    # Момент № 1
    # При установке бандла по умолчанию текущий файл находится в app/config/routes
    # Затем при компиляции контейнера YamlLoader парсятся все файлы в указанной папке, а в самом лоадере
    # в списке доступных ключей нет ключа routes_to_expose, поэтому падает исключение

    # Момент № 2
    # При переносе файла в app/packages, если оставить resources, будет падать исключение, так как в конфе бандла
    # такого ключа нет.

    # Регулярка имени роутов, регулярка по самому роуту почему-то не работает
    routes_to_expose:  [ 'api_(\S+)' ]
