version: '3'

services:
  web:
    image: nginx
    volumes:
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'

  node:
    image: timbru31/node-alpine-git:14
    volumes:
      - ./assets:/assets
    working_dir: /assets
    command: yarn serve

  app:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    volumes:
      - .:/var/www/html/

  db:
    image: postgres:12
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=payroll
      - POSTGRES_PASSWORD=payroll
      - POSTGRES_DB=payroll
