version: '3'

services:
  web:
    image: nginx
    volumes:
      - ./public:/var/www/html/public
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'
  app:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    volumes:
      - .:/var/www/html/
  db:
    image: postgres:12
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=payroll
      - POSTGRES_PASSWORD=payroll
      - POSTGRES_DB=payroll
